login:

  url: 'http://127.0.0.1:3000/login'
  user:
    type: xpath
    ele: "//*[@type='text']"

  pas:
    type: xpath
    ele: "//*[@type='password']"

  sub:
    type: xpath
    ele: "//*[@type='submit']"

  u_send:
    text: 'kkkkkk'

  p_pas:
    text : '55555'
